
GCC_HOME=/usr/local/gcc-7_4_0
CMAKE_HOME=/usr/local/cmake-3.14.1-Linux-x86_64

export PATH=${GCC_HOME}/bin/:${CMAKE_HOME}/bin/:$PATH

# for build time, find include files and link libraries
export CPATH=${GCC_HOME}/include/:$CPATH
export LIBRARY_PATH=${GCC_HOME}/lib64/:${GCC_HOME}/lib/:$LIBRARY_PATH

# for runtime
export LD_LIBRARY_PATH=${GCC_HOME}/lib64/:${GCC_HOME}/lib/:$LD_LIBRARY_PATH
