
FROM nginx

#replace default.conf for nginx
COPY *.conf /etc/nginx/conf.d/

# labels
LABEL maintainer="wangyoucao577@gmail.com"
LABEL org.opencontainers.image.source https://github.com/wangyoucao577/containers
