
#FROM mcr.microsoft.com/windows:20H2
FROM mcr.microsoft.com/windows/servercore:ltsc2019

#TODO: 



LABEL maintainer="wangyoucao577@gmail.com"
LABEL org.opencontainers.image.source https://github.com/wangyoucao577/containers
