apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: clone-code
          image: "{{ .Values.image.name }}"
          command: ["/bin/bash"]
          args: ["-c", "cd / && git clone https://github.com/ApolloAuto/apollo.git"]
          volumeMounts:
            - mountPath: /apollo
              name: apollo-root
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.httpPort }}
              protocol: TCP
            - name: ssh
              containerPort: {{ .Values.container.sshPort }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.container.sshPort }}
            initialDelaySeconds: 5
            periodSeconds: 1
            failureThreshold: 1000
          livenessProbe:
            tcpSocket:
              port: {{ .Values.container.sshPort }}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.sharedMemory }}         
            - mountPath: /dev/shm
              name: shared-memory
            {{- end}}
            - mountPath: /apollo
              name: apollo-root
      volumes:
        {{- if .Values.sharedMemory }}         
        - emptyDir:
            {{- toYaml .Values.sharedMemory | nindent 12 }}
          name: shared-memory
        {{- end}}
        - emptyDir:
          name: apollo-root
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
