apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.container.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.sshPort }}
      targetPort: {{ .Values.container.sshPort }}
      protocol: TCP
      name: ssh
  selector:
    app: {{ .Release.Name }}
