name: Build Docker - nginx-file-server 

on: 
  push:
    branches:
    - 'master'
    - 'release/**'
    tags:
    - '**'
    paths:
    - 'docker/nginx-file-server/**'

env:
  IMAGE_NAME: nginx-file-server
  DOCKERFILE_PATH: docker/nginx-file-server/

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set IMAGE_TAG env # env IMAGE_TAG=BranchName-CommitID-Timestamp
      run: echo IMAGE_TAG=$(basename ${GITHUB_REF})-$(echo ${GITHUB_SHA} | cut -c 1-7)-$(date -u +"%Y%m%d") >> ${GITHUB_ENV}
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - name: Build & Publish to Github Container Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.actor }}/${{ env.IMAGE_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_PACKAGES_TOKEN }}
        registry: ghcr.io
        snapshot: false
        workdir: ${{ env.DOCKERFILE_PATH }}
        tags: "latest,${{ env.IMAGE_TAG }}"
        buildargs: "IMAGE_TAG=${{ env.IMAGE_TAG }}"

    - name: Build & Publish to DockerHub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        snapshot: false
        workdir: ${{ env.DOCKERFILE_PATH }}
        tags: "latest,${{ env.IMAGE_TAG }}"
        buildargs: "IMAGE_TAG=${{ env.IMAGE_TAG }}"
